### ISSUE TITLE
Add floating settings trigger

### ISSUE THREAD

**Issue by jelen07** [orestbida/cookieconsent#111]
### Feature request
Add native support of "floating setting's trigger" like ie. CookieHub. 

<img width="380" alt="CookieHub floating trigger" src="http://g.recordit.co/09CyU2AuwO.gif">

### Proposed solution
Beside `consent modal` and `consent settings` add new "element" ie. `trigger` in `gui_options`. It could trigger `consent settings` by default. But it could also trigger `consent modal` as well depending on the configuration. Configuration could contain other settings like

1. layout `minimal|expanding`
2. position `bottom|middle|top + left|right|center`
4. transition - `zoom|slide`
5. target - `consent_modal|settings_modal (default)`
6. icon - base64
7. class - custom CSS class

The translation should be configurable via `languages`. The solution should contain default styles/js like beautiful consent and settings modals.

### Current solution
At the moment, it's possible to create a trigger on anchor or button tag via data attribute (`data-cc="c-settings"`). Example JS snippet of creating trigger from GTM tag:

```js
// Create settings toggle
var tt = document.createElement("a");
tt.setAttribute('class', 'link');
tt.setAttribute('type', 'button');
tt.setAttribute('data-cc', 'c-settings');
tt.innerHTML = 'Cookie consent';
document.getElementsByTagName("footer")[0].appendChild(tt);
```

And code toggle functionality manually.

### UX improvements
When showing one element, the other(s) should be hidden:
1. When `consent_modal` is visible, `settings_modal` and `trigger` should be hidden.
2. When `trigger` is visible, `settings_modal` and `consent_modal` should be hidden.
3. When `settings_modal` is visible, `consent_modal` and `trigger` should be hidden.

**Comment by orestbida** [comment]
I don't hate the idea, but I don't love it either. If possible I'd like to avoid adding too many optional features like this for a more lightweight plugin.

I'd like to leave this issue open to hear other's opinions

**Comment by tillsanders** [comment]
I feel the same way, @orestbida. I‘ve seen and used buttons like this with other solutions. It was nice to have the option to revise my choices easily. It would also be helpful if these buttons have a uniform design so they can be recognised more easily. So that would be in favour of an integration in CookieConsent.

But yes, it would also add more weight to the plugin. And the user experience of these buttons was mixed for me. The interfered with other elements and got in the way of the content, especially on mobile. So I went with a simple link in the footer.

Since it is possible to implement such a feature using the plugin‘s API, I would not integrate it. But it is still a nice addition for some and lately I have often thought that things like these would make a great plugin for CookieConsent. Maybe CookieConsent could provide a small collection of addons to offer functionality like this? That would also help maintain the core codebase.

Cheers
Till

**Comment by orestbida** [comment]
@tillsanders Yes! 

With v3 I'd like to focus on the modularity aspect which - if done properly - would allow features like this to be easily implemented without worrying too much about the "chunkiness" of the plugin. One could choose whatever features/addons they need based on their setup/framework.
