### ISSUE TITLE
Toggle should be colored (red | green)

### ISSUE THREAD

**Issue by xstable** [orestbida/cookieconsent#14]
First: I love "cookieconsent". Great work. Thank you!

It would be nice if you could add something, that the user knows, what the state of the switch is.

Mabe but in front or behind the switch "allowed" | "denied", or make it colorfull
![image](https://user-images.githubusercontent.com/1778068/113903978-d73d2600-97d1-11eb-93fb-46eff6a51425.png)

BTW: On / Off is not the best wording, I only insert it because it was short enough ;)

**Comment by orestbida** [comment]
@xstable 100% agree, the state of the toggles is not clear at all as of now, especially with the current color scheme.
I would avoid adding text (on-off, enabled-disabled) because of the **little space** (as you mentioned) but also so that users won't **need to specify/translate the label** on the configuration object.

So i was thinking something like [this style](https://assets.justinmind.com/wp-content/uploads/2020/05/yes-no-toggle-example.png) which should convey properly the toggle status.

**Comment by xstable** [comment]
@orestbida yep, thats looks much better. Maybe add an option for developers (by adding some css-classes) to overload the component with own colors.
