### ISSUE TITLE
CCPA Compliance

### ISSUE THREAD

**Issue by DanielAbsi** [orestbida/cookieconsent#145]
Does it follow CCPA (California Consumer Privacy Act) as well as GDPR?

**Comment by orestbida** [comment]
Yes, since it uses the opt-in method and doesn't track users without their consent. Once/If consent is given, users can opt-out in any moment.

With that being said, you can make it ccpa/gdpr non-compliant by removing/hiding the "secondary button" used for the reject action or to manage individual preferences. So it really depends on how you configure it.

**Comment by trymeouteh** [comment]
https://github.com/orestbida/cookieconsent/pull/509

If cookieconsent is CCPA compliant. I created a pull request to add CCPA compliant to the readme for others to know that this is compliant with CCPA.
