### ISSUE TITLE
Autoclear work only on change state not if first check diable category

### ISSUE THREAD

**Issue by pivoVaRy** [orestbida/cookieconsent#159]
Hi,
autoclear work only if check enable and after change state to disable catagory cookie.
But is better for first run if all is disable clear all cookies in remove cookie table becaouse many cookie have valid date to year 2022.

**Comment by orestbida** [comment]
Hi @pivoVaRy,

if cookies were not deleted after opt-out, it means that there are issues with your config. Listed cookies should be properly removed on opt-out and running the cleanup function on every page-load shouldn't be needed!

If you want to "forcefully" clear the cookies, you can use the `.eraseCookies()` (check [docs.](https://github.com/orestbida/cookieconsent#api-methods) for more specific details and options) method inside the `onAccept` callback function:
```javascript
cookieconsent.eraseCookies(['cookie1', 'cookie2']);
```

Could you post your configuration so that I may understand why cookies are not being deleted?

**Comment by TooMuchTaurine** [comment]
I have seen the same issue.... What about the scenario that we are ust implmenting this code now and existing cookies exist with 2 year expiration?  Or the scenario where by the cookie are set in a different application / subdomani but still served up here.

I think the default behaviour when rejecting cookies should be to clear them out.

SO this line likely need sot be changed.
https://github.com/orestbida/cookieconsent/blob/350d295ae72ef3ce4358d51435908dabe89f7c2a/src/cookieconsent.js#L827

**Comment by havlicekv** [comment]
I had same issue. I had GA cookies with 2 years expiration and after refusing consent, they were still in browser storage. I solved it by calling eraseCookie in onAccept function like @orestbida adviced before.

**Comment by orestbida** [comment]
I will not change the default behaviour of the autoclear option but I will be considering on adding another valid option for `autoclear_cookies`, perhaps something like:

```javascript
autoclear_cookies: 'always'
```

which would always run the clean-up function on every page load.

**Comment by orestbida** [comment]
I've received a few private messages regarding this option. Since this isn't exactly a breaking-change, I'll go ahead and make @pivoVaRy's proposed behaviour the default (and only) one.
