### ISSUE TITLE
CSS architecture is messy

### ISSUE THREAD

**Issue by bomastudioweb** [orestbida/cookieconsent#168]
First: thank you, the plugin works really well!

Plase consider improving CSS architecture, here some examples:

1) Consider doing the possible to have a smaller CSS footprint. Less style equals to less errors, easier to customize, and better overall speed (consider we're adding upon existing css codebase). 

2) Avoid styling using ID selector and "too generic" class names (example: ".slide"). 
The solution might be using a "unique" prefix to style all your classes:
.cookieconsent--classone { }
.cookieconsent--classtwo { }

3) Class names are not human readable, so it's a bit hard to customize for users

Thanks a lot for your attention: I am open to discussion and willing to contribute to this, already awesome, project.

**Comment by orestbida** [comment]
Hi @bomastudioweb,

yes, I totally agree on the fact that the css structure is messy!

The main issue is that there are a lot of themes — mainly wordpress ones — which apply a lot of rules globally with a high specificity.

E.g.: a `button` element with the following unique class `.cc__button--accept` would be easily messed up by a rule like this:
`.body button: { border: 4px solid red }`.

To fix this I would have to write a higher specificity rule, perhaps something like `.cc .cc__button--accept` which:
1. defeats the purpose of having unique class names
2. does not really fix the specificity issue since there can be even higher (global) specific rules than the one I created

So it boiled down to either:
* using `id`'s (higher specificity than classes)
* using the `!important` clause everywhere

The `!important` clause  approach (always discouraged) would have been more effective but it had one major drawback: significant increase in filesize. So I went with the `id` route; I also shortened each class to something — as you mentioned — more cryptic, to reduce the filesize.

Considering the fact that you don't have control over a website's css "framework" and the css rules used by its plugins (you should expect the worst) — how would you address this issue (specificity) while still having a decent css structure/framework?

**Comment by ikeblaster** [comment]
Woudn't be possible to use shadWoudn't be possible to use shadow DOM? Then you would have no conflicts with "outer" styles.ow DOM? Then you would have no conflicts with "outer" styles.
