### ISSUE TITLE
Page scripts loaded when consent is rejected

### ISSUE THREAD

**Issue by MartinMystikJonas** [orestbida/cookieconsent#176]
Would it be possible to have page scripts loaded on inverse condition? We would like to have one version of script loaded when user gives consent and if he revokes consent we would like to load different version. In our use case we want to load Google Analytics either with cookies enabled of with cookies disabled (measiring only basic data without cookies) based on user choice. I think about something like support for ```data-cookiecategory="!analytics"```

**Comment by orestbida** [comment]
Hi @MartinMystikJonas ,

I think I got your idea. This looks similiar (if not the same) to a **"legitimate interest"** option. 

I don't know if it's worth implementing this feature, since the same behaviour can be achieved with the next release (v2.8) using the `mode` option:

![ewew](https://user-images.githubusercontent.com/34487268/147882269-d517a21f-9132-46d6-9c1d-cff2e6c2edae.PNG)

You would need to have at least one category marked as essential/readonly and enabled by default: e.g. a `'necessary'` category:

```javascript
// ...
toggle: {
    value: 'necessary',
    enabled: true,
    readonly: true
}
// ...
```

Then you could do something like this:
```html
<script type="text/plain" data-cookiecategory="necessary">
    if( !cookieconsent.allowedCategory('analytics') ){
        // code logic with minimal tracking
    }
</script>

<script type="text/plain" data-cookiecategory="analytics">
    // code logic with full tracking (cookies) 
</script>
```

With that being said, I'd like to leave this open to hear other's opinions.

**Comment by MartinMystikJonas** [comment]
Well in your example minimal tracking code will be run before user made any choice right? And if he enables analytics it will then run full tracking code? Therefore two tracking codes will be run on single visit. We want something a bit different. We want simple way to run either minimal or full tracking after user made his choice. It could be done with custom handlers but I thought it could be useful feature for others. Scripts with ```!category``` should be run when user confirms his choice of not allowing analytics (eithet denies or closes popup with analytics denied by default)

**Comment by orestbida** [comment]
My bad, I interpreted it as having an "always on" tracking even without consent. In this case it'd be simpler, since you don't need the 'mode' option at all.

I think that the issue of having the 2 tracking codes executed still applies in your case, regardless of the `mode` option. 

The user could:
1. initially reject analytics (or reject all categories) => script under `!analytics` would execute
2. change preferences and accept analytics (or accept all categories) => script under `analytics` would execute

Correct me If I'm wrong; this feature request is something related more to convenience/simplicity rather than being a completely new needed functionality which can't be achieved with the suggested approach.

**Comment by MartinMystikJonas** [comment]
Yes I think it could be achieved by event hooks (onAccept, onChange, onFirstAction) that would then execute either minimal or full tracking.

There is no way to prevent all scenariou that would duplicate visits but we want to solve it for most common scenario whrn user visits web for first time and accepts cookies.

**Comment by wzol** [comment]
I really like the idea and the logic of `!analytics` syntax - but not yet have an idea of the double count in case of changing preferences. Although depending on sites I don't think that is so common.

Maybe a check after level change could do the trick - on change setting only load `analytics `if the previous level wasn't `!analytics`?

**Comment by MartinMystikJonas** [comment]
Well in some cases it is preffered to have double events than have only no-cookie event. So it might be better to have it somehow configurable. Maybe another parameter like data-cookiemutex=id and only one script with given mutex id can be executed on page. Without mutex scripts will be run on every change.

**Comment by orestbida** [comment]
As of `v3.0.0-rc.1`, you can use the discussed `!` to run the script on opt-out:

```html
<script type="text/plain" data-category="analytics">
    console.log("analytics enabled");
</script>

<script type="text/plain" data-category="!analytics">
    console.log("analytics disabled");
</script>
```

Note: The script with the `!` before the category, will be executed only if the category was previously enabled/accepted.
