### ISSUE TITLE
Type text/plain not valid in HTML validator.

### ISSUE THREAD

**Issue by Arnoost** [orestbida/cookieconsent#189]
Error: A script element with a src attribute must not have a type attribute whose value is anything other than the empty string, a JavaScript MIME type, or module.

<script type="text/plain" data-cookiecategory="analytics" async src="https://www.googletagmanager.com/gtag/js?id=

Any help, please?

**Comment by orestbida** [comment]
Hi @Arnoost,

the `type="text/plain"` attribute is required, as this is what effectively disables the script. Using `type="text/plain"` is common practice for cookie consent managers.

You should pass validation errors using one of the following methods:

1. Remove the `async` attribute and change `src` to `data-src`
2. Load `gtag` using the plugin's `loadScript()` method (example):
    <br>
    ```html
    <script type="text/plain" data-cookiecategory="analytics">
    cookieconsent.loadScript('https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID', function(){
        // Script loaded, do something
        
        window.dataLayer = window.dataLayer || [];
        function gtag(){window.dataLayer.push(arguments);}
        gtag('js', new Date());
        
        gtag('config', 'GA_MEASUREMENT_ID');
    });
    </script>
    ```
3. Load `gtm` instead of `gtag` (you might need to change your configuration), since `gtm` can be loaded using the inline way (without the src attribute)
4. Same as the second option, but this time use the `.loadScript()` method inside the `onAccept`/`onChange` callbacks (might be  difficult if you don't know much about javascript or how the plugin works)

The logic of all these options is simple: if you care about validation, avoid using the `src` attribute together with `type="text/plain"` attribute.

**Comment by Arnoost** [comment]
Thanks a lot
