### ISSUE TITLE
Add ability to pass translation object after library initialization

### ISSUE THREAD

**Issue by alex-ketch** [orestbida/cookieconsent#230]
> Mhm, I'd like to avoid this because with v3 I want to keep the configuration settings separated from the translation (as much as possible).

_Originally posted by @orestbida in https://github.com/orestbida/cookieconsent/issues/219#issuecomment-1021705078_

---

Your above comment caught my attention and thought I'd raise a separate issue for it.
One use case that I'd love to see supported would be to have a way to pass in a translation configuration object after `cookieconsent.run(…)` has been called.
Less essential, but still would be nice, would be to be able to re-instantiate the library with a new config object (besides translation) too.

Use case being that the translations are loaded dynamically based on the user's chosen locale, thus translations for locales user doesn't care about aren't loaded—lower bandwidth, faster loads.
However, this causes problems at the moment as this library expects all translations to be in the config before calling `run`, and as far as I could tell there's no way to pass in a new configuration after the fact.

Thanks for considering, and let me know if you'd like me to elaborate on any of the above.

**Comment by orestbida** [comment]
Hi @alex-ketch,

yes, I agree! I'd like to add better support for external language files (e.g. `en.json`, `it.json` ...) and especially to allow the languages/translations to be loaded dynamically and individually. I don't know if it's worth adding a method to _**pass translation object after library initialization**_, I'm more towards keeping the entire configuration inside the `.run({})` method

As for the _**to be able to re-instantiate the library with a new config object**_ request, I don't know how I feel about this. Scripts which were once enabled (those loaded using the `page_scripts` option) will stay enabled regardless of your new preferences.


**_"However, this causes problems at the moment as this library expects all translations to be in the config before calling run, and as far as I could tell there's no way to pass in a new configuration after the fact."_**

If you can detect before-hand what your locale is then you can load only that needed translation. Since this plugin doesn't handle external `.json` files currently, I'm gonna use `.js` files containing the translations.

`en.js`:
```javascript
window.ccTranslations = window.ccTranslations || {};

window.ccTranslations.en = {
    title: 'title in english',
    description: '...',
    // ...
};
```

`it.js`:
```javascript
window.ccTranslations = window.ccTranslations || {};

window.cc_translations.it = {
    title: 'title in italian',
    description: '...',
    // ...
};
```
```javascript
const cc = initCookieConsent();
const htmlLang = document.documentElement.lang.substring(0, 2).toLowerCase();

switch(htmlLang){

**Comment by orestbida** [comment]
Hi @alex-ketch,

yes, I agree! I'd like to add better support for external language files (e.g. `en.json`, `it.json` ...) and especially to allow the languages/translations to be loaded dynamically and individually. I don't know if it's worth adding a method to _**pass translation object after library initialization**_, I'm more towards keeping the entire configuration inside the `.run({})` method

As for the _**to be able to re-instantiate the library with a new config object**_ request, I don't know how I feel about this. Scripts which were once enabled (those loaded using the `page_scripts` option) will stay enabled regardless of your new preferences.


**_"However, this causes problems at the moment as this library expects all translations to be in the config before calling run, and as far as I could tell there's no way to pass in a new configuration after the fact."_**

You can make this work currently, but it is not ideal! If you can detect before-hand what your locale is then you can load only that needed translation. Since this plugin doesn't handle external `.json` files currently, I'm gonna use `.js` files containing the translations.

`en.js`:
```javascript
window.ccTranslations = window.ccTranslations || {};

window.ccTranslations.en = {
    consent_modal: {
        title: 'title in english',
        description: '...',
        // ...
    },
    // ...
};
```

`it.js`:
```javascript
window.ccTranslations = window.ccTranslations || {};

window.cc_translations.it = {
    consent_modal: {
        title: 'title in italian',
        description: '...',
        // ...
    },
    // ...
};
```
`cookieconsent-init.js`:
```javascript
const cc = initCookieConsent();
const htmlLang = document.documentElement.lang.substring(0, 2).toLowerCase();

switch(htmlLang){
    case 'en': cc.loadScript('en.js', runPlugin); break;
    case 'it': cc.loadScript('it.js', runPlugin); break;
    default: cc.loadScript('en.js', runPlugin);
}

function runPlugin(){
    cc.run({
        // ...
        languages: window.ccTranslations
    });
}
```

Based on the same above logic, you can also dynamically add a new translation! For example, if you are currently using the `en` language, but you'd like to load the `it` translation and use that instead, you could do something like this:

```javascript
cc.loadScript('it.js', function(){
    // add new translation
    cc.getConfig('languages').it = window.ccTranslations.it;
    
    // update modal's language
    cc.updateLanguage('it');
});
```
Note that I haven't tested this so It might not work at all (although it should)!

**Comment by orestbida** [comment]
@alex-ketch,

v3 now adds support for external json translation files, loaded dynamically based on the current locale: [demo](https://github.com/orestbida/cookieconsent/blob/5034c108ae01aff883708e9fd1b78c772095790c/demo/demo_iframemanager/cookieconsent-init.js#L106-L108)
