### ISSUE TITLE
Use a build system

### ISSUE THREAD

**Issue by superbiche** [orestbida/cookieconsent#254]
Using something like Webpack / Vite to build the app from source would make it easier for people to contribute, build either umd/esm modules and make it compatible with other modern build tools / frameworks.

This would also make it easier to migrate the package to TypeScript.

**Comment by superbiche** [comment]
@orestbida I'd be happy to work on this if you have too much on your plate for v3

**Comment by tillsanders** [comment]
In my experience, webpack is powerful but the configuration is a pain in the ass. Vite is also powerful but far easier to handle. However, given that there were discussions to convert to TypeScript, we might not even need a bundler, just the TypeScript compiler or maybe Babel (which could also help with browser support).

**Comment by superbiche** [comment]
Compared to Webpack, Vite is : 
1. Lighter
2. Easier to configure
3. Faster
4. Makes smaller bundles (uses Rollup)
5. Makes building for many targets (ESM, UMD, CDN script...) very easy  

I've been using Webpack for the past 5+ years and I'm starting all my new projects with Vite / migrating the older ones I still maintain to it. 

I use it daily so I'd be happy to implement it on this project.  

> I think the build system will be the last step
Honestly it would be a great plus to have it as soon as we can, as it makes development much more comfortable, allows to split  the code early to avoid code duplication, make it more organized and thus easier to maintain.

Finally we could build an easy to setup development environment to make it easier for people to contribute.

I know I'm very opinionated about this but trust me, using this kind of tool from the beginning is a developer's life changer.

**Comment by superbiche** [comment]
@orestbida regarding IE 11 support, is this a requirement for one of your projects? I'm wondering if it's really that relevant as support will end in June 2022. 

> Any vulnerability that is discovered after June 2022 will not be fixed

IE11 is reported at 0.47% global usage in Feb 2022. I'd say sticking to ES5 only because of IE11 should be considered more thoroughly.

**Comment by superbiche** [comment]
@superbiche we could use https://github.com/vitejs/vite/tree/main/packages/plugin-legacy for this (if using Vite is on the table of course)

**Comment by tillsanders** [comment]
Another advantage of vite is the new test runner vitest. It's very fast and uses the same configuration as vite. So no seperate configuration for building and testing the code which is the case with the also popular webpack/jest combination.

That being said – I find that some projects use a bundler just for the sake of it but don't actually need one. At the moment this library doesn't even have dependencies which is the main reason to use a bundler. TypeScript with optionally Babel simply doesn't need a bundler for most use-cases. It would only slow down build time and might even increase filesize a tiny bit.

TL;DR: I would go with TS + Babel and add Vite + Vitest only if needed. Could also happen later. Set up an npm script for building and no one will even notice 😄

**Comment by orestbida** [comment]
@tillsanders yes, I also like the idea of using TS + Babel, keeping things simple, at least for now. 

Knowing that I would also like to set up unit tests later on (after the conversion to typescript), would you recommend going with TS + Babel + Jest or completely switch to Vite? I would personally go with the former option.

**Comment by superbiche** [comment]
I really don't see how setting up TS + Babel + a build minifier could be more simple than using Vite. It comes preconfigured for TS, a single plugin adds Babel without needing to configure it, and builds with Rollup for chunk splitting / tree shaking / optimization. Regarding the bundle size, I'm not sure using TS + Babel would be more efficient than Vite + Compatibility layer + Rollup, except if you use Rollup for the build. Again, it's configured with sane defaults in Vite. Why bother write configuration files for all this when you can get it in a matter of minutes?

If you want to add tests, that's another good reason to use Vite: as @tillsanders suggested there's [Vitest](https://github.com/vitest-dev/vitest) which is like Jest but way simpler and more powerful.

**Comment by tillsanders** [comment]
> I really don't see how setting up TS + Babel + a build minifier could be more simple than using Vite.

It really depends on what you're doing (as always). Bundlers are super useful and Vite is amazing. But people throw a bundler at everything these days without really considering if they actually need it. Many people who start using web technologies today don't even understand the difference between a bundler and a build system. Yes, Vite is simple, much simpler than webpack also. But even a simple tool can create a lot of problems – all it needs is an annoying bug that costs you hours to figure out.

When I'm writing a small module for work, for example, I sometimes use only TypeScript because that is such a simple setup. Just run `tsc --init` and you're up and running. No need for bundling, since that happens in a higher module that actually builds code to run on the client. No need for minification for the same reason. No need for Babel since I can set the `target` to a JavaScript version going back as far as ES3. No bundler is faster and more reliable than no bundler ;)

That being said, cookieconsent of course does need minification as it can be used simply by loading it with `<script src>`. And a test runner with better TypeScript compatibility than jest would also be nice. So Vite and Vitest would be a nice choice. Or Rollup and Jest. Or Parcel. I'm just saying that you don't need to use a bundler, and we shouldn't choose an approach or library just because it's the current default. All solutions discussed will be fine and we should go with what @orestbida prefers or feels comfortable with, because he is the one doing all the work.

**Comment by orestbida** [comment]
I guess I could try setting up vite myself, and only then decide what to do!
