### ISSUE TITLE
Settings (cookies preferences) in privacy page instead of popup

### ISSUE THREAD

**Issue by Ghaleb-alnakhlani** [orestbida/cookieconsent#275]
Hi is it possible to have the cookies settings embedded in the privacy page? 
And instead of using a toggle for the services change it to a checkbox?
Thank you

**Comment by orestbida** [comment]
Technically speaking, yes, you can. You would — however — need to manually re-create the buttons, checkboxes and labels ...

The easiest way to create buttons connected to the plugin is by using the `data-cc` attributes as described [here](https://github.com/orestbida/cookieconsent#available-data-cc-actions). Alternatively, you could tie the buttons to the [API](https://github.com/orestbida/cookieconsent#api-methods) methods for more control.

When the user navigates to the privacy page, you would need to fetch the current user's preferences — using `.getUserPreferences()`  — in order to set the state of the checkboxes (checked/unchecked) correctly.

Then, based on which button is pressed:
- accept all button => check all checkboxes
- reject all button => uncheck all checkboxes (except those marked as necessary)
- save preferences button => retrieve all accepted categories — based on the current checked checkboxes — and pass the array of categories to the `.accept()` method.

You're in for quite a bit of work! Check the docs. for examples regarding the API methods.

**Comment by Ghaleb-alnakhlani** [comment]
Great I would appreciate it if you can provide a snippet of an example.
I will try to simplify the steps more. In the main cookie banner, there will be only two buttons `Accept all` or `reject all`, and a `more settings link`. When `more settings link` is pressed it will take you to the settings section on the privacy page. Lets say we have to options Google analytics checkbox and Facebook pixle checkbox and a button to `save preferences`.
