### ISSUE TITLE
Close button for cookieconsent

### ISSUE THREAD

**Issue by t0is** [orestbida/cookieconsent#291]
Hi. 

I was  wondering if it is possible to add a "X" (Close) button for the main cookie consent window. 

I know there's one in the prefferences tab, you can also disable that, but could you somehow enable that in the main window? 

In Italy, for ex, this is a requirement by law and also, it is pretty convenient for users. 

Thanks for advice.

**Comment by orestbida** [comment]
Hi @t0is,

based on the official website [Garante della Privacy](https://www.garanteprivacy.it/) — the cookie banner must have:

> - A warning to the effect that the website uses technical cookies as well as (subject to user’s consent) profiling cookies or other tracking tools along with information on the relevant purposes (short information notice);
> 
> - A link to the privacy policy containing the extended information notice and mentioning any additional recipients of the personal data, data storage periods and how to exercise the rights under the GDPR; 
> 
> - A warning to the effect that if the banner is closed (e.g. by clicking on the ‘X’ on its top right corner) the default settings are left unchanged and therefore browsing can continue without cookies or other tracking tools other than technical ones.
> 
> Accordingly, the banner will have to contain the following in order to obtain valid consent: - The command referred to above (e.g., an ‘X’ placed on the top right corner) to close the banner without giving one’s consent to the use of cookies or other profiling techniques and by keeping default settings;
> 
> - A command (button) to accept all cookies or tracking tools;
> 
> - A link to an additional dedicated area where the user can select, individually, the functionalities, the third parties, and the cookies that user consents to install, and where the user can either consent to the use of all cookies (if such consent has not already been given) or withdraw his/her consent, also once and for all. In this regard, a good practice consists in using a graphical sign, an icon or any other technical arrangement to flag (e.g. in the footer of each domain page) the status of the consent declarations given by each user, and to enable changing or updating such declarations

- https://www.garanteprivacy.it/temi/cookie
- https://www.garanteprivacy.it/garante/document?ID=9679270
- [Linee Guida Cookie e altri strumenti di tracciamento - INFOGRAFICA](https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/9734291)

As I understand it, the "X" button symbol is merely a suggestion, and it is not the only valid way to reject cookies.
There are many other sources that claim the same thing, including large CMP solutions such as [Iubenda](https://www.iubenda.com/en/help/31246-italy-new-cookie-rules).

If this were not the case, virtually all of the existing CMP solutions would not be in compliance with the Italian Cookie Law.

- They do not provide the ability to add an X button in the upper right corner of the banner.
- They let you place an X button, but it is either small, difficult to click or hardly visible.

That said, the next version of the plug-in will allow you to add a large/visible X button in a specific layout. 
Here is a preview: https://github.com/orestbida/cookieconsent/pull/288;

Personally, I would use a "Reject all" button that speaks for itself rather than an "X" button.
