### ISSUE TITLE
Incompatible types in 2.8 version

### ISSUE THREAD

**Issue by literat** [orestbida/cookieconsent#349]
Hi,

we are [upgrading from 2.8.0 to 2.8.3](https://github.com/lmc-eu/cookie-consent-manager/pull/250) version of this library and I came across [some incompatible](https://github.com/lmc-eu/cookie-consent-manager/runs/7520320409?check_suite_focus=true) types that are used in this version.

**Problems are caused by these types:**
- missing `cookie_name` key
- missing `level` key in `SavedCookieContent`. This is renamed in version 3 to `categories`. The key `categories` is present in types.
- required type `cookie_table_headers` in `SettingsModalLanguageSetting`, which, I think, should not be required, added in https://github.com/orestbida/cookieconsent/pull/335

I can help with fixing these issues and create pull-request to fix them. Please let me know if these are unintentional bugs that I could solve by adding those keys and making the last one not required.

Thank you for this library and your work on it ♥️

**Comment by orestbida** [comment]
Hi @literat,

since v2.8.1 the `level` field was (unintentionally) renamed to `categories`. v2.8.1 was released a few months after v2.8.0, and I completely forgot about this change — which was supposed to be present only in the v3 version.

https://github.com/orestbida/cookieconsent/blob/819914ce9d7fb1ac1d2fe222d4a03697a7988640/src/cookieconsent.js#L1147-L1149

At this point, reverting it back might not be a good idea, because it would create even more confusion.

**Comment by literat** [comment]
@orestbida Ok, thanks for the explanation. I've updated the underlying PR to respect this change.

**Comment by orestbida** [comment]
Thanks a lot for your contribution!
