### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by ElGigi** [orestbida/cookieconsent#38]
Do you plan to create an NPM package?
Lots of advantages to manage version upgrade.
Thx

**Comment by orestbida** [comment]
Hi, @ElGigi 

I have no plans on bringing this on npm, or at least not in the near future.

**Comment by sirko-uhl** [comment]
> Hi, @ElGigi
> 
> I have no plans on bringing this on npm, or at least not in the near future.

This is very sad. NPM brings a lot of advantages for Updates of this nice Package.

**Comment by orestbida** [comment]
@sirko-uhl don't get me wrong, I never said I won't do it, in fact porting this plugin to npm isn't anything hard. I'm simply too busy during this period.

**Comment by ibrahimcesar** [comment]
@sirko-uhl I know you are well meaning, but please don't put this kind of burden in the maintainer. Since the license is MIT, you could build your port of NPM of @orestbida's work. Also, I could help if you are interested into.

**Comment by tillsanders** [comment]
I started to distribute the library through the NPM Registry. Due to naming conflicts, it is not available under `cookieconsent` or `cookieconsent.js` but as [`vanilla-cookieconsent`](https://www.npmjs.com/package/vanilla-cookieconsent).

```sh
npm i vanilla-cookieconsent
yarn add vanilla-cookieconsent
```

I made no further changes in [my fork](https://github.com/tillsanders/cookieconsent) and don't intend to do so. I will try to publish up-to-date versions, but obviously it would be great if @orestbida would take over some day. If that happens, I'm gladly handing over the NPM handle so there is no interruption for anyone.

Also, let me say that this is a really cool library with great a great user interface and I'm impressed what has been accomplished using vanilla JavaScript 👍  Thanks Orest!

**Comment by orestbida** [comment]
@tillsanders Nice! Will be adding your link into the Readme for upcoming users!

**Comment by tillsanders** [comment]
@danieltvaz Hi, maybe this issue will help you get started? #42

**Comment by tillsanders** [comment]
v2.5.0 is now available on the NPM Registry: <https://www.npmjs.com/package/vanilla-cookieconsent>

**Comment by superbiche** [comment]
Can this issue be closed?

**Comment by orestbida** [comment]
@superbiche, yep!
