### ISSUE TITLE
Using text/plain on script-tags is not allowed according to w3 validator

### ISSUE THREAD

**Issue by melker** [orestbida/cookieconsent#394]
You suggest using script tags like this:
"<script type="text/plain" data-cookiecategory="analytics" src="analytics.js" defer></script>" (example from https://github.com/orestbida/cookieconsent)

We have been doing that but w3 validator does say it is invalid html. 

I made a report about this to the validator (as I interpreted the spec then same way as you) but now they say it is still incorrect to use it that way.

Ref to my iusse report to the validator:
https://github.com/validator/validator/issues/1379

**Comment by melker** [comment]
Note that right now there is a patched version of the validator online but they will revert that patch. (See info in the linked issue.)

**Comment by tillsanders** [comment]
That is regrettable. But since this is becoming quite common, the standard will eventually adapt to the reality or offer a better solution. So for the meantime, is this really an issue? It is not syntactically invalid, so it will still parse fine. Also, it is not an issue for end users. Until I'm missing something, this is annoying at worst, no?

Thanks for your effort though!

Side note: there is a really good talk about the resilience of HTML and how browsers handle invalid code: https://youtu.be/MchVtvUIUjQ

**Comment by melker** [comment]
Having valid html is relevant to us. The main validation tool for that is the w3-validator. So... for us, this is an issue.

**Comment by orestbida** [comment]
Hopefully future standards will improve the type-src "issue".

@melker In the meantime, you could use the — undocumented — `data-src` attribute, instead of `src` (also check out #189).

**Comment by orestbida** [comment]
w3 validator has been updated and no longer throws error: https://github.com/validator/validator/commit/bbc7d80a050c3fab17029491afbe49fecc04cc3c
