### ISSUE TITLE
Uncaught SyntaxError: missing name after . operator

### ISSUE THREAD

**Issue by tobiashaas** [orestbida/cookieconsent#399]
Beta 3.0.0 rc8

Hey I wanted to test the script today and I get the following error in the console!

It is WordPress in use with the Bricks Builder.

I don't understand what's wrong here, so I'm sharing it with you guys and I hope it's just a bug

column: 9851 - using this file -> cookieconsent.umd.js
textContent=e.replace(/<.*>.*<./.*>/gm,'')

**Comment by orestbida** [comment]
Hi @tobiashaas,

the correct `RegExp` is
`/<.*>.*<\/.*>/gm`

instead of (your value)
`/<.>.<./.*>/gm`

This is the original line (the minified `cookieconsent.umd.js` is also ok):
https://github.com/orestbida/cookieconsent/blob/373186804261d7d93b9daf4fc93eadf233ad9b16/src/core/modals/preferencesModal.js#L563

There could be something on your end which is trying to process/compress the file, causing this issue.

**Comment by tobiashaas** [comment]
I guess I made a mistake when copying! Many Thanks
