### ISSUE TITLE
"Your Consent Details" & "Detect Broweser Language"

### ISSUE THREAD

**Issue by JohnCirby** [orestbida/cookieconsent#435]
Hi Orest!

**First of all, thank you for your awesome work !!!**

I am trying add these two information to preferences modal
I am using v3.0.0-rc11.

My config: 

`                        {
                            "title": "Your consent details",
                            "description": "<p>Consent ID: <span id=\"consent-id\">-</span><p>consent Date: <span id=\"consent-timestamp\">-</span></p><p>Last update: <span id=\"last-consent-timestamp\">-</span></p>"
                        },`

`                        {
                            "title": "Detect browser language",
                            "description": "<input type=\"checkbox\" id=\"auto-language\" name=\"autoLanguage\" class=\"hidden\" checked><div class=\"auto-language__details\"><p>Detected language: <span id=\"detected-language\">-</span></p><d>Translation found: <span id=\"translation-found\">-</span></div>"
                        },`

HTML Elements are visible but empty.
[https://ibb.co/M69hzGY](https://ibb.co/M69hzGY)

What's wrong?

Thanks for the help

**Comment by orestbida** [comment]
Hi @JohnCirby,

you need javascript code to make this work. 

This is how you [retrieve and inject consent details into the modal](https://gist.github.com/orestbida/62ac9787123c841fa2448e91573bf22b).

As for the "Detect browser language" section, it would require you to reload the page — since you cannot update the plugin's configuration once it has been executed. There is also no easy way to retrieve the current language from the plugin.

**Comment by JohnCirby** [comment]
Hi,

Thanks for the quick response and sorry for such a simple question but I've really been googling and trying different options for several days. Maybe it will help someone else.. 

Best regards
