### ISSUE TITLE
Add documentation on how to use cookieconsent in React/Next.js and React Native Web

### ISSUE THREAD

**Issue by agape-apps** [orestbida/cookieconsent#44]
This is an excellent cookie management script. Thank you so much for writing and maintaining it!

Please add documentation on how to use cookieconsent from within React based projects.

Currently I am using cookieconsent successfully on a Next.js website and in a React Native Web App (Expo Bare Workflow) under the same domain name. I am not sure if the way I am integrating cookieconsent is the correct or best way, but I was able to get everything working with Google Analytics and cookieconsent.

**Comment by orestbida** [comment]
Hi @agape-apps,

currently this is a vanilla js script only, hopefully a react component will be published on npm in the future!
For the time being, I would load the script just as I showed in #42. The only difference would be that instead of `mount()` (used by vue), you'd need to run the script inside `componentDidMount()`. If you know of a better way to load external scripts in react, let me know!

**Comment by jp-olvera** [comment]
Hope this helps anyone whose trying to connect cc with react, its based on what @orestbida did in the [42](https://github.com/orestbida/cookieconsent/issues/42)

`useEffect(() => {
    const callCC = () => {
      var cc;
      try {
        cc = (window as any).initCookieConsent();
      } catch (error) {
        console.error(error);
      }
      if (cc) {
        cc.run({
          // your code here
        });
      }
    };

    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@v2.5.0/dist/cookieconsent.js';
    script.type = 'application/javascript';
    document.head.appendChild(script);
  
    const timer = setTimeout(() => {
      callCC();
    }, 1000);

    return () => {
      clearTimeout(timer);
    };
  }, []);`
