### ISSUE TITLE
Block Cookie first loading website dev question

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [orestbida/cookieconsent#449]
Hello, 

I love this extension, nevertheless I block on some things, how to block a script at the loading of the site coming for example from a WordPress plugin ? or we do not have the hands on the <script ... tag ?

Do you have an example ?

REALLY THANKS

**Comment by RockyKev** [comment]
I just used this library for a internal wordpress plugin within my company. Through research, a lot of the cookie consent plugins do it 'dynamically' but not really, where the plugin stores all the script tags in the WP database, then blocks them manually on load until consent is given. All of them are paid features, so I'm only making a rough guess.

I was lucky enough to be able to modify all the injection/tracking scripts within the theme of the site, and have the plugin focus more on the consent functionality. Seemed a lot easier.

Thoughts on your use-case, identify the plugins that are tracking/creating cookies, and migrating them into this? That way, you can control it's flow. For example, rather than using a Google Analytics plugin, remove it and include GA in this library. Very tedious but that's the only way I can think of within WordPress.

Of course, i'd love other ideas too!

**Comment by ALTITUDE-DEV-FR** [comment]
I have partly succeeded in doing this, I am developing my own WordPress plugin for the mandatory RGPD in France.

The site admin can define his policy page.
The site admin can choose which cookies to delete on loading by the cookie key.

finally the user can then delete, rectify, or apply the cookies
