### ISSUE TITLE
Make cookieconsent work with the Hush-Plugin

### ISSUE THREAD

**Issue by haecksenwerk** [orestbida/cookieconsent#45]
The Safari browser shows just a blank page if the Hush-Plugin is installed. If one deactivates the plugin, the website content and the cookieconsent overlay show up after a refresh.

https://oblador.github.io/hush/

**Comment by orestbida** [comment]
Hi @haecksenwerk,

I don't have the slightlest clue of how the hush plugin. It could automatically accept, reject or hide/dismiss cookie cosent popups (without action) which, in all cases, is not the right take from my point of view, as it should be up to the user to make such a choice (especially with GDPR in eu). 

While consent notices might look a pain i.t.a**(and many of these are a real pain i.t.a** due to the infinite ammount of options like toggles, tabs and hidden tabs) they are needed by law. 

If you feel like you absolutely need to make the hush plugin "work" with this cookie solution, please create an issue in hush' repo instead, since this "issue" is outside my scope and interest.

**Comment by haecksenwerk** [comment]
Hi @orestbida,

In general, I share your philosophy on the handling of Cookie-Popups. But let's be true, if you take internet hygiene seriously and regularly delete your cookies and browser cache, then these overlays are just more than annoying when you visit again, and a plugin like "Hush" is just very pleasant.

It's just that I've never noticed any problems using the hush-plugin on other sites (except that the cookie overlay code here and there was smart enough to ignore the plugin and appear anyway), but the demo site of the 'cookieconsent' plugin and the page I made with it are just broken since they just display a blank page in the browser. So I thought you might want to consider thinking about potential root causes, as it could possibly have other page effects as well. But of course, I also understand that this is now the typical chicken-and-egg back-and-forth of a problem.
