### ISSUE TITLE
Cookieconsent v3 : TypeError: can't convert undefined to object

### ISSUE THREAD

**Issue by dngraphisme** [orestbida/cookieconsent#478]
Hello @orestbida ,

I'm coming back to you because I updated your library with version 3 and I still have an error that I don't understand.

This is how my webpack stack is written:

init.js > I run all my functions
cookie.js > concerns your library

To start the import is not really specified and that changed with v3: I found via this topic: https://github.com/orestbida/cookieconsent/issues/441

Regarding cookie.js > here is what I wrote :

```
import * as CookieConsent from 'vanilla-cookieconsent';

export const cookie = {
    init: function () {
        const CookieConsent = initCookieConsent();
        CookieConsent.run({
            // conf basic inside
        })
    },
}
export default cookie;
```

 if I put back: `const CookieConsent = initCookieConsent();`

I end up with this error > **ReferenceError: initCookieConsent is not defined**

If I comment it out I get this: **TypeError: can't convert undefined to object**

-------

Regarding init.js > here is what I wrote :

`let cookieNotice;`

and in a function that I call `firstLoad()` I run this : 

`cookieNotice = cookie.init();`

I declared cookieNotice to use it in other function in this file because I work with barbaJS.

-------

I'm struggling to understand, because I had no problem with the old version. You could help me ?

thanks in advance, Nicolas

**Comment by orestbida** [comment]
v3 is not compatible with v2. [The configuration, API etc. have all been reworked](https://github.com/orestbida/cookieconsent/issues/252).

The easiest way to upgrade is to start from 0, rather than trying to adapt the v2 config.

There are now 2 `.js` builds.

* cookieconsent.esm.js (recommended)
* cookieconsent.umd.js which you can use just like v2 (without using "import").

If you can, use the esm variant, as it's more flexible.

`initCookieConsent` no longer exists as it's not needed anymore.

You can directly import the plugin anywhere, and use its methods via CookieConsent.<method-name>, as long as you make sure that `CookieConsent.run({})`. has been called (with a valid config).

This is how I'd adapt it:

```javascript
// cookie.js
import { run } from 'vanilla-cookieconsent';

export const cookie = {
    init: () => {
        run({
            // conf basic inside
        })
    },
}

export default cookie;
```

```javascript
// another.js
// import only needed methods
import { showPreferences } from 'vanilla-cookieconsent';
```

Checkout the [API page](https://cookieconsent.orestbida.com/reference/api-reference.html#showpreferences) for all available  methods.

You can also find example configs. in the [/demo](https://github.com/orestbida/cookieconsent/tree/v3.0-beta/demo) dir. or live demos on [Stackblitz](https://stackblitz.com/@orestbida/collections/cookieconsent-v3).

**Comment by dngraphisme** [comment]
Hello @orestbida ,

Indeed, everything has changed, and it's my fault I looked badly.

Great work as usual.

Normally it's ok, I'll come back here if needed!

Thanks again, nicolas
