### ISSUE TITLE
[Feat]: Allow customisation of script `type` on accept (mainly for use with Partytown)

### ISSUE THREAD

**Issue by spacedawwwg** [orestbida/cookieconsent#487]
https://github.com/orestbida/cookieconsent/blob/540c235fd2b945d3e49d152f209762fed2716796/src/cookieconsent.js#L1624

It would be nice to be able to change the type to `type="text/partytown"` and trigger a `ptupdate` after consent is given

https://partytown.builder.io/partytown-scripts#dynamically-appending-scripts

## Idea 💡

on a script you add `data-type="text/partytown"`

change line 1624 to:

```JS
// 99% of the time people will want the default
curr_script.type = curr_script.getAttribute('data-type') || 'text/javascript';

```

then a user can handle their own callback

```JS

//...
cc.run({
    // ...
    onAccept: function(cookie){
        window.dispatchEvent(new CustomEvent('ptupdate'));
    },
    // ...
});
```

What do you think?

**Comment by orestbida** [comment]
Hi @spacedawwwg,

this feature is already implemented in [v3](https://github.com/orestbida/cookieconsent/tree/v3.0-beta). However, since this is a very tiny code addition, we can also implement it in v2.

**Comment by spacedawwwg** [comment]
Boom 💥

**Comment by preetamslot** [comment]
@orestbida 
I tested this in 2.9.0 and 3. But it looks like only the first script is activated, other scripts get ignored. Am I doing something wrong? 

If you look at the screenshot, first script is now active `type="text/partytown-x"`. the second is still `type="text/plain"`

![image](https://github.com/orestbida/cookieconsent/assets/5420582/c25508af-2b92-4a7c-bbda-f134b548ca59)


Thanks

**Comment by orestbida** [comment]
@spacedawwwg,

the first script in the screenshot has a `src` attribute, and the current implementation will wait for the `onload/onerror` event to fire before loading other script tags, to ensure that all script tags are loaded sequentially.

https://github.com/orestbida/cookieconsent/blob/1efe109194f38143d074e66bb7ce53df70397c62/src/utils/scripts.js#L164-L170

The `onload/onerror` event — however — is never fired due to the invalid javascript mime type: `type="text/partytown-x"`. This also prevents all the other scripts from loading.

**Comment by orestbida** [comment]
@spacedawwwg please try [this branch](https://github.com/orestbida/cookieconsent/tree/allow-custom-mime-type-on-script-tags-with-src-attribute) and let me know if that fixes it!
