### ISSUE TITLE
How implement Facebook pixel?

### ISSUE THREAD

**Issue by tdrzewosz** [orestbida/cookieconsent#52]
Hello, could you explain how to implement Facebook Pixel, please? Thanks

kind regards

**Comment by orestbida** [comment]
Hi @tdrzewosz,

to easily manage any third party scripts, you must:

1. enable the `page_scripts` option in your config. :
   ```javascript
   cookieconsent.run({
      ...
      page_scripts: true,
      ...
   });
   ```
2. copy-paste the tracking code provided by facebook. You can place it anywhere you want. (before or after the cookieconsent script tag)
3. add/change the script type to `text/plain` (so that the script is disabled initially) and also add a valid `data-cookiecategory` attribute like so:
   
   ```javascript
   <script type="text/plain" data-cookiecategory="analytics">
   ```
   Note: the value inside `data-cookiecategory` must be alredy defined in your config. This must be one of the values inside of the `toggle` objects.

<br>

You can see a full example with this approach, in the second demo (example with gtag and clarity): [app.js](https://github.com/orestbida/cookieconsent/blob/26ca5b3c2b5448da76c4555b4bdafa015631a9e1/demo/app2.js#L27) , [index.html](https://github.com/orestbida/cookieconsent/blob/26ca5b3c2b5448da76c4555b4bdafa015631a9e1/demo/index2.html#L544):

**Comment by tdrzewosz** [comment]
Thanks, works! perfectly
