### ISSUE TITLE
Delete cookies not working

### ISSUE THREAD

**Issue by tdrzewosz** [orestbida/cookieconsent#53]
Hello, if I disable locally (local webserver) tracking the cookies will be deleted after refresh. perfect! Now I have deployed all files to webspace, but the cookies are still available. I need help, please and sorry my bad English.

**Comment by orestbida** [comment]
Hi @tdrzewosz,

I need some details like:
- version of the cookieconsent
- your current cookieconsent config. 
- in which browser/s are you facing this issue
- are there any visible errors on the browser console?

if possible, provide the domain/subdomain where you're facing this issue so that I can better look into it.

**Comment by tdrzewosz** [comment]
My fault, wrong domain. It works, now. thanks

**Comment by timkrins** [comment]
I was coming up against my cookies not deleting also.

Discovered that it was because even though Chrome inspector says the cookie domain for a cookie was `subdomain.example.com`, the domain that it was created with was actually blank.

I needed to add a blank string into the usual domains array in `_autoclearCookies()`.
