### ISSUE TITLE
Facebook Pixel Cookie

### ISSUE THREAD

**Issue by tdrzewosz** [orestbida/cookieconsent#54]
Hello, If I have denied all cookies, then all cookies are deleted! Works, but If I have changed next page only _fbp cookie is visible. I don't know why. 

`    
    <script type="text/plain" data-cookiecategory="analytics">
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return; n = f.fbq = function () {
              n.callMethod ?
                n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
            n.queue = []; t = b.createElement(e); t.async = !0;
            t.src = v; s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
          }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '4711');
          fbq('track', 'PageView'); 
        console.log("loaded gtm.js");
    </script>
    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=4711&ev=PageView&noscript=1"/></noscript>`

Thanks!

**Comment by tdrzewosz** [comment]
Workaround: After delete cookies, window.location.reload();

**Comment by orestbida** [comment]
Some scripts might re-create their cookies right after they've been deleted! For example clarity.js always does this. 

The only workaround I could come up with (as you did) was indeed a **forced reload** so that the current active script/s, responsible for the cookie re-creation, would no longer run. 

You could try using the built in `reload` option like showcased in the [demo app.js](https://github.com/orestbida/cookieconsent/blob/master/demo/app2.js):

https://github.com/orestbida/cookieconsent/blob/26ca5b3c2b5448da76c4555b4bdafa015631a9e1/demo/app2.js#L137-L142

**Comment by tdrzewosz** [comment]
` reload: 'on_disable' ` now it works. Thanks!

Great Consent Tool, great coder!!!!!! thanks
