### ISSUE TITLE
Consider splitting the script loader into a separate package or file

### ISSUE THREAD

**Issue by karptonite** [orestbida/cookieconsent#66]
First, let me say that, so far, I love this package. I'm just starting to wire it up, but it seems that you've given this a lot of thought.

One thing I've run into (I hesitate to call it an issue) is that the script loader that is part of the package seems to be completely separate from the cookie consent functionality. There isn't any real reason for them to share an object. While loading a script is a common thing we want to do in response to consent being granted, there are a lot of ways to accomplish this. As far as I can tell, I can include cookieconsent either entirely or not at all in my code; I can't exclude the script loader, and while it isn't a huge feature, it is some unnecessary code.

I suggest that you consider splitting the script loader into another package (or even find another existing package that serves that purpose). You could still suggest loading that package, and use it in your examples, but I think that both packages would benefit from a separation of concerns.

Of course I may be missing some way they are integrated that makes this entire suggestion moot, in which case, please disregard this suggestion and carry on. :)

**Comment by orestbida** [comment]
Hi @karptonite,

Interesting point, as I myself have asked this question!

The main reason why the plugin's file size is bigger than necessary, is mainly because it was designed with the idea of being “very cross-browser”, in fact it uses — at most — es5 functions/syntax. We could argue if it's worth supporting older/legacy browser nowadays, but I'm going to leave that topic for another day, just to not drag this discussion too much.

Regarding only the `loadScript()` function:
- for a developer it is something not necessary to have — just as you stated — and I totally agree with you! 
- for a newbie — though — it could be of some help (maybe ...)

I think the `loadScript` function is small enough (40/1700 lines) to not be too much of a “dead weight”. Another problem is that the removal of this feature is surely a “breaking change”, and could throw off some less expert users (as there isn't even a proper debug/error handling component)

The true upgrade to reduce the overall file size would be to just drop support for older browsers and use es6+ syntax (clearer, shorter, neater), perhaps in a future v3.0 release!

Note:
there's also an internal function called `_loadScripts` which — unlike the above discussed `.loadScript()` — is required to properly manage third party scripts

**Comment by karptonite** [comment]
Makes sense to me!

Dropping support for older browsers (or any feature) is definitely a 3.x release. I agree that `loadScript()` is not a lot of code, and it isn't really a serious concern. I think I had it in my mind that `_loadScripts()` could also be removed, but while that is also a feature that could theoretically be done without (for users that, for example, handle the loading of scripts manually with `loadScript()`), splitting it out would be a lot more trouble, and would make the package(s) more difficult to use.

**Comment by orestbida** [comment]
Yes, `_loadScript()` makes sure that the (configured) scripts run in the same order the user declared them; it can manage any js snippet without having to:

1. move them inside the onAccept/onChange methods
2. adapt the code

This type of “loose” dependency also allows for a smoother transition to another solution (should this plugin not fit their needs)

I'm glad I didn't merge the [iframemanager](https://github.com/orestbida/iframemanager) into this plugin (some users had asked for it to be embedded) as that would have been quite a big chunk of dead weight for many users!
