### ISSUE TITLE
[Feat]: Extend hideFromBots function

### ISSUE THREAD

**Issue by HemiCZ** [orestbida/cookieconsent#687]
### Description

The current function only checks bots with user-agent like `/bot|crawl|spider|slurp|teoma/i`.

However, Google uses other bots with different names, such as:
- Google-InspectionTool
- GoogleOther
- Google-Extended
- Chrome-Lighthouse

https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#googlebot-desktop
https://stackoverflow.com/a/78137919

**Comment by HemiCZ** [comment]
@orestbida  I'm not sure if I understand it, but in "Google-InspectionTool" is no "bot" key, or?

**Comment by orestbida** [comment]
My bad, I didn't check the second half of the services (the ones you actually listed). You are right, the plugin won't detect these bots. 

With that said I think it's fine keeping it as is since the main point of this option is to prevent the indexing of the modal's content (indexing is done by other bots afaik).
