### ISSUE TITLE
Add third button

### ISSUE THREAD

**Issue by SoftCreatR** [orestbida/cookieconsent#79]
It would be great if there would be an optional, third button so that one can provide the options

Accept all / Accept necessary
Decline / Accept necessary
Settings / Accept necessary

like most other consent tools provide. At least in Germany, it is necessary to have an accept button and a decline button with equal weight, if the accept button enables all options.

So I'm thinking about something like that:

![image](https://user-images.githubusercontent.com/81188/135505791-dc97be0a-eae1-4d1a-811a-1176f0101794.png)

**Comment by orestbida** [comment]
Hi @SoftCreatR,

the reason why there's not a 3rd optional button is because adding one would “ruin” the layout of those modals with very little text. Modals with the `box` layout would become quite ugly;  I'd have to either make all the 3 buttons super small or re-arrange them vertically. 

With that being said, you can still add your own elements, by either injecting your own links/buttons or simply by putting them inside the description field:

![dsdsdsd](https://user-images.githubusercontent.com/34487268/135522816-8a808cae-7fd9-417b-9626-4fabb6df2750.PNG)

As for the equal weight argument, I think it should be possible by modifying the css variables' values inside the .css file. I don't think it's worth adding an ad-hoc option in the javascript configuration as it is something quite specific/niche.

With that being said, I'd like to leave this issue open to hear more opinions!

**Comment by SoftCreatR** [comment]
I already switched to the textual settings link.

**Comment by dramocz** [comment]
Hi, thanks for the great script! I would also welcome the possibility of displaying a third button for quick rejection of cookies. In the Czech Republic, the legislation requires the same level of acceptance and rejection of cookies in the first step.

**Comment by jelen07** [comment]
@dramocz You're able to achieve that with two buttons - first is `accept_all`, the second is `accept_necessary` and the settings trigger could be in the text.

That will be a completely legal setup. What do you think?

**Comment by dramocz** [comment]
@jelen07 Thanks for the tip. I've inserted the link in the text, I think that's a sufficient solution.

**Comment by lmc-product** [comment]
> Hi, thanks for the great script! I would also welcome the possibility of displaying a third button for quick rejection of cookies. In the Czech Republic, the legislation requires the same level of acceptance and rejection of cookies in the first step.

Really? I am from CZ as well as there is no such requirement in law as far I know. 

See also  European Data Protection Board available how to handle consents: https://edpb.europa.eu/sites/default/files/files/file1/edpb_guidelines_202005_consent_en.pdf or https://edpb.europa.eu/sites/default/files/files/file1/edpb_guidelines_202005_consent_cs.pdf

So basically you should be able to give consent or not give consent in "equal prominence" display. Which I think Accept only necesssary cookies is good enough.

**Comment by SoftCreatR** [comment]
Using it like this is absolutely fine with GDPR:

![Screenshot_20211129-131927_Edge](https://user-images.githubusercontent.com/81188/143867180-54857619-7437-4587-b79e-a9084e3c5191.jpg)

**Comment by paolonet** [comment]
hi, i had the same problem and this is my solution:

after cookieconsent.run() i simply append a new button to “c-bns” div. Here with jquery:

 `
cookieconsent.run(“stuff to do”);
$('#c-bns').append('<button type="button" data-cc="c-settings" class="c-bn c_link" aria-haspopup="dialog">Settings</button>');
`

**Comment by paolonet** [comment]
hi, i had the same problem and this is my solution:

after cookieconsent.run() i simply append a new button to “c-bns” div. Here with jquery:

`cookieconsent.run(“stuff to do”); `
`$('#c-bns').append('<button type="button" data-cc="c-settings" class="c-bn c_link" aria-haspopup="dialog">Settings</button>');`

not so elegant, but it's a good workaround

@orestbida Great work!

**Comment by Rombecchi** [comment]
Here in Italy, our GDPR requires us to put an "X" in the top right corner of the banner to refuse all cookies except the necessary ones.
I am asking if it would be possible to add this possibility.
[https://www.gpdp.it/web/guest/temi/cookie](https://www.gpdp.it/web/guest/temi/cookie)

**Comment by ondequadre** [comment]
> I tried the solution you suggested, the third button appears correctly but then if I click it it doesn't work, it doesn't open the settings window.



> hi, i had the same problem and this is my solution:
> 
> after cookieconsent.run() i simply append a new button to “c-bns” div. Here with jquery:
> 
> `cookieconsent.run(“stuff to do”); ` `$('#c-bns').append('<button type="button" data-cc="c-settings" class="c-bn c_link" aria-haspopup="dialog">Settings</button>');`
> 
> not so elegant, but it's a good workaround
> 
> @orestbida Great work!

**Comment by htmlplanet974** [comment]
It doesn't work because the addlistener instructions have already been called ...

Here is my solution:

For the third button I took the links already inserted in the banner at the end of the text and moved it in position, making it become a button:

`var el = $('#c-inr-i #c-txt .cc-link').remove();
el.removeClass('cc-link').addClass('c-bn');
$('#cm.bar #c-bns').prepend(el);`

For the question of the closing "X" I added a new element that works as an alias of the "Reject all" button, in practice through a new observer I click on the button already created previously:

`$('#cm.bar #c-inr').prepend('<button type="button" id="c-bn-close" class="c-bn c_link">X</button>');
$('#c-bn-close').on('click', function() { $('#c-s-bn').click(); });`

**Comment by Iris92** [comment]
Great work [htmlplanet974](https://github.com/htmlplanet974)
Thanks

**Comment by ondequadre** [comment]
Thanks htmlplanet974, it works fine, for now I will use this solution while waiting for the new version 3 to add this functionality.

**Comment by eyecatchup** [comment]
I can not share the detailed report, but we've got the current implementation reviewed by 2 privacy law firms, because we wanted to use the library for a governmental web project.

Long story short: The current implementation seems **not** compliant with European law.

Most member states require equally prominent buttons for acceptance and rejection right on the initial screen. No nudging allowed.

Here's a great visualization of the current (2022) situation ([details & refenrences](https://www.iubenda.com/en/help/23672-gdpr-cookie-consent-cheatsheet)):
![Bildschirmfoto 2022-03-25 um 14 14 46](https://user-images.githubusercontent.com/845131/160128236-70147c17-aa51-4f0c-b724-a2db429f016a.png)

Relevant links (some in German):

- https://www.finch.com/blog/cookie-consent-tools-and-nudging/
- https://lfd.niedersachsen.de/startseite/themen/internet/datenschutzkonforme-einwilligungen-auf-webseiten-anforderungen-an-consent-layer-194906.html
- https://www.vzbv.de/sites/default/files/downloads/2020/11/25/lg_rostock_15.09.2020.pdf

**Comment by orestbida** [comment]
We can finally close this issue! All the above discussed layouts/options (including a footer for links) are implemented in v3 (beta)!
