### ISSUE TITLE
Google tag manager - Cookies not being removed

### ISSUE THREAD

**Issue by webicient** [orestbida/cookieconsent#81]
I have put in google tag manager script that only triggers when third party cookies is enabled. And in google tag manager I got third party scripts like google analytics and some other scripts.

Everything seems to be working fine, except when the user disables third party script in the cookie settings after they have accepted third part cookies. 

The cookies that tag manager has set (google analytics and others) still remains. Google analytics stops tracking but the cookies still remain in the browser. Should the cookies not be removed when disabling?

I have set the cookies that google tag manager gives in the cookie tables.

**Comment by orestbida** [comment]
Hi @webicient,

could you share your configuration?

**Comment by orestbida** [comment]
Cookie names need to match in order for them to be deleted properly, and since `_li_id.b85f` is different than `_li_id` the plugin very likely skips it entirely since it can't find it.

If you don't know what the rest of the cookie name will be, you can try and enable the `is_regex` option which will allow the plugin to **delete all of the cookies starting with `_li_ses` and `_li_id`** strings:

```javascript
{
    col1: "^_li_id",
    col2: "leadinfo.com",
    col3: "2 år",
    col4: "Leadinfo",
    is_regex: true
},
{
    col1: "^_li_ses",
    col2: "leadinfo.com",
    col3: "Session",
    col4: "Leadinfo",
    is_regex: true
}
