### ISSUE TITLE
Allow enabling/disabling of single services

### ISSUE THREAD

**Issue by SoftCreatR** [orestbida/cookieconsent#85]
While this tool does a good job already, it would be nice, if one could enable/disable single services. As of now, you can only enable/disable a whole category, which is often not desired.

**Comment by SoftCreatR** [comment]
That's what I was thinking of :)

**Comment by orestbida** [comment]
I am moving this to the v.3.0.0 milestone as it's something which requires more time/thought to be properly implemented

**Comment by OndraM** [comment]
In fact, **there is no such requirement for per-service enable/disable**  in GDPR. Also most of the national EU data protection bureaus themselves state that **per-purpose** (analytics/marketing/...) granularity is enough.

The [European Data Protection Board Guidelines](https://edpb.europa.eu/sites/default/files/files/file1/edpb_guidelines_202005_consent_en.pdf) clearly states this (article 42, 44...):
> 42. A service may involve multiple processing operations for more than one purpose. In such cases, the
data subjects should be free to choose which purpose they accept, rather than having to consent to a
bundle of processing purposes. 
> 44. (...) When data processing is done in pursuit of several purposes, the solution to comply with the conditions for valid consent lies in granularity, i.e. the separation of these purposes and obtaining consent for each purpose.

This is also presumed by [GDPR itself](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679), eg. article 32:

>  Consent should cover all processing activities carried out for the same purpose or purposes.

So no, to comply with GDPR, you don't have to be able to reject each individual cookie. You must be able to reject each individual purpose though.

I'm not sure whether you must list all used cookies somewhere - but even if so, this could be done on some other separate and static Privacy page, this don't have to be done as a feature of this plugin.

**Comment by orestbida** [comment]
This feature is available in `v3.0.0-rc.1`.

You can now define a service like so:
https://github.com/orestbida/cookieconsent/blob/87a23a52bda6a3da0c53839550742103a8e12aa7/demo/demo_iframemanager/index.html#L41-L43

or using the internal config. object:
https://github.com/orestbida/cookieconsent/blob/87a23a52bda6a3da0c53839550742103a8e12aa7/demo/demo_iframemanager/cookieconsent-init.js#L83-L92

Check out the [docs](https://cookieconsent.orestbida.com/reference/configuration-reference.html#categories-services) (work in progress) for more details.

**Comment by SoftCreatR** [comment]
A demo would be nice :)

**Comment by SoftCreatR** [comment]
Ah, I see. Thank you ver much.

**Comment by eistruhe** [comment]
I've just tested the latest [iframemanager demo](https://github.com/orestbida/cookieconsent/tree/v3.0-beta/demo/demo_iframemanager) which has two services in the analytics category. Wouldn't it be necessary to move the "Name", "Description" and "Provider" into each service instead of the whole category? Because I could register completely different services and list them in one category, right?
