### ISSUE TITLE
Can I somehow put the primary button to the rightmost position in box layout?

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#96]
As I checked other consent dialogs the primary button is usually the rightmost button, also it is probably better for UX as most users are right handed, and it is closer to the scrollbar. Any way I can achieve this?

Can I do any harm with this?

```
#cc--main #c-bns {
    display: flex;
    justify-content: space-between;
    flex-flow: row-reverse;
}
```

**Comment by orestbida** [comment]
Hmm, I don't know about your approach but — in case it doesn't work — you can check #83. 

I might add a `swap_buttons` option in a future release for cases like yours.

**Comment by wzol** [comment]
I think I stay with the flex solution, it seems more friendly for me. Just for the info it needs a `@media all and (min-width: 600px)` or something like that as it is not nice in mobile view.

**Comment by jelen07** [comment]
Since I'm using this configuration for `consent_modall`

```
primary_btn: {
    text: 'Accept All',
    role: 'accept_all'              // 'accept_selected' or 'accept_all'
},
secondary_btn: {
    text: 'Settings',
    role: 'settings'                 // 'settings' or 'accept_necessary'
}
```
That creates something like

<img width="605" alt="Snímek obrazovky 2021-11-20 v 7 54 17" src="https://user-images.githubusercontent.com/2346295/142717801-c42170c1-12a2-4001-9912-425cefac0bcd.png">

I would like to configure buttons position over settings in JS instead of styling to achieve UX like on the image below because it's "more natural" from some perspective - the primary button on the right.

<img width="570" alt="Snímek obrazovky 2021-11-20 v 7 59 36" src="https://user-images.githubusercontent.com/2346295/142717803-9cfc8702-f109-4f40-9017-8ec93d2c3a92.png">
